### ISSUE TITLE
Issues with save

### ISSUE THREAD

**Issue by winterdd01** [dubravcik/pbixrefresher-python#24]
I too am having an issue when the script attempts to save. Below is the output. Thanks in advance!

(Power BI Version: Version: 2.72.5556.701 64-bit (August 2019) running on windows 10)

Saving
Traceback (most recent call last):
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwayn\AppData\Local\Programs\Python\Python37-32\Scripts\pbixrefresher.exe\__main__.py", line 9, in <module>
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\site-packages\pbixrefresher\pbixrefresher.py", line 67, in main
    type_keys("%1", win)
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\site-packages\pbixrefresher\pbixrefresher.py", line 13, in type_keys
    element.type_keys(char)
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\site-packages\pywinauto\base_wrapper.py", line 936, in type_keys
    self.verify_actionable()
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\site-packages\pywinauto\base_wrapper.py", line 681, in verify_actionable
    self.verify_enabled()
  File "c:\users\dwayn\appdata\local\programs\python\python37-32\lib\site-packages\pywinauto\base_wrapper.py", line 692, in verify_enabled
    raise ElementNotEnabled()
pywinauto.base_wrapper.ElementNotEnabled

**Comment by Eilerss** [comment]
I have tried pbixrefresher on 2 .pbix, one small and one big file, and on the small one worked. I think the problem is that when it tries to save, the file is still refreshing or exiting the refresh window.

**Comment by winterdd01** [comment]
Thanks for the idea. I did try with a simple file and it did save successfully. I then tried with a large file and it failed. I bumped up the timeouts several times. It is still failing on the large file...

**Comment by LevonPython** [comment]
You can try this way, it is quite simple.
https://github.com/LevonPython/PbiRefresher
