### ISSUE TITLE
Trouble with timing

### ISSUE THREAD

**Issue by viniciusmauser** [dubravcik/pbixrefresher-python#4]
C:\Users\vinicius.maureira\Documents\Testing\Pipeline Cybertrust>pbixrefresher Cybertrust-Pipeline.pbix
Starting Power BI
Identifying Power BI window
Refreshing
Saving
Publish
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\timings.py", line 447, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pbixrefresher.py", line 72, in <module>
    publish_dialog.child_window(title = WORKSPACE).click_input()
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\application.py", line 351, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    raise e.original_exception
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\timings.py", line 425, in wait_until_passes
    func_val = func(*args)
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\application.py", line 209, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'auto_id': 'KoPublishToGroupDialog', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - 'Cybertrust-Pipeline - Power BI Desktop', WindowsForms10.Window.8.app.0.17ad52b_r8_ad1, 722594>, 'backend': 'uia'}

don´t refresh and don't save

**Comment by dubravcik** [comment]
I've updated the publish key strokes which were introduces in PBI 2.53.4954.621 64-bit (December 2017). Please update to latest release from pip and check if it works for you.
Thanks

**Comment by viniciusmauser** [comment]
Hi, it's 83,33% ok, but still having problema to refresh:
Starting Power BI - OK
Identifying Power BI window - OK
Refreshing - NO OK
Saving - OK
Publish - OK
Exiting - OK

Maybe is a problema with timing? too short the time maybe?

**Comment by Dppprasad** [comment]
Hello @viniciusmauser & @dubravcik 

What did you guys do for timeout Error? I also get the same. Any idea how to get rid of this will highly appreciate.  Thank you so much

`C:\#AutoRefresh\Top100>python top100pbixrefresher.py
Starting Power BI
Identifying Power BI window
Refreshing
Traceback (most recent call last):
  File "top100pbixrefresher.py", line 95, in <module>
    main()
  File "top100pbixrefresher.py", line 59, in main
    win.wait("enabled", timeout = 300)
  File "C:\Users\dbulugahamulle\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\application.py", line 501, in wait
    lambda: self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\dbulugahamulle\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\timings.py", line 367, in wait_until
    raise err
pywinauto.timings.TimeoutError: timed out`

**Comment by KumailQazi** [comment]
Its working perfectly fine. I have put refresh iteration every 2 mins and it worked perfect. :)

**Comment by Ubaidbutt** [comment]
I am facing exactly the same issue. The code breaks at Publish and asks "Do you want to save your changes" and throws an error.
